# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
      - image: mongo:3.2.4
      - image: postgres:9.5.5
      - image: redis:4.0.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: wordcraft
          POSTGRES_PASSWORD: ""      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        command: |
          echo "create role postgres with login;" | psql -U postgres
          echo "create database wordcraft;" | psql -U postgres

      - run: yarn test
