module.exports = {
  1:
  [
    { word: 'carnivore', level: 1 },
    { word: 'herbivore', level: 1 },
    { word: 'omnivore', level: 2 },
    { word: 'omnipotent', level: 1 },
    { word: 'omniscient', level: 1 },
    { word: 'herbivore', level: 2 },
    { word: 'herbicide', level: 1 },
    { word: 'regicide', level: 1 },
    { word: 'homicide', level: 2 },
    { word: 'omnivore', level: 2 },
    { word: 'omnipotent', level: 2 },
    { word: 'omniscient', level: 2 },
    { word: 'carnivore', level: 2 },
    { word: 'herbivore', level: 2 },
    { word: 'regicide', level: 1 },
    { word: 'herbicide', level: 1 },
    { word: 'homicide', level: 2 },
    { word: 'carnivore', level: 1 },
    { word: 'herbivore', level: 1 },
    { word: 'omnivore', level: 2 },
    { word: 'omnipotent', level: 3 },
    { word: 'omniscient', level: 4 },
    { word: 'herbivore', level: 2 },
    { word: 'herbicide', level: 3 },
    { word: 'regicide', level: 1 },
    { word: 'homicide', level: 2 },
    { word: 'omnivore', level: 1 },
    { word: 'omnipotent', level: 2 }
  ],
  3:
  [
    { word: 'bicycle', level: 1 },
    { word: 'tricycle', level: 1 },
    { word: 'biped', level: 1 },
    { word: 'quadruped', level: 1 },
    { word: 'centipede', level: 1 },
    { word: 'millipede', level: 1 },
    { word: 'pedal', level: 1 },
    { word: 'pedestrian', level: 1 },
    { word: 'tripod', level: 2 },
    { word: 'impediment', level: 1 },
    { word: 'quadruped', level: 2 },
    { word: 'bicycle', level: 1 },
    { word: 'biped', level: 1 },
    { word: 'centipede', level: 2 },
    { word: 'millipede', level: 2 }
  ],
  2:
  [
    { word: 'carnivore', level: 1 },
    { word: 'herbivore', level: 1 },
    { word: 'omnivore', level: 2 },
    { word: 'omnipotent', level: 1 },
    { word: 'omniscient', level: 1 },
    { word: 'herbivore', level: 2 },
    { word: 'herbicide', level: 1 },
    { word: 'regicide', level: 1 },
    { word: 'homicide', level: 2 },
    { word: 'omnivore', level: 2 },
    { word: 'omniscient', level: 2 },
    { word: 'omnipotent', level: 2 }
  ],
  4:
  [
    { word: 'bicycle', level: 1 },
    { word: 'biped', level: 1 },
    { word: 'triathlon', level: 1 },
    { word: 'bicentennial', level: 1 },
    { word: 'century', level: 1 },
    { word: 'decade', level: 1 },
    { word: 'millenium', level: 2 },
    { word: 'biannual', level: 2 },
    { word: 'quadruped', level: 1 },
    { word: 'biceps', level: 1 },
    { word: 'triceps', level: 2 },
    { word: 'quadriceps', level: 1 },
    { word: 'trident', level: 6 },
    { word: 'trilogy', level: 4 }
  ],
  5:
  [
    { word: 'microscope', level: 2 },
    { word: 'microcosm', level: 2 },
    { word: 'microbiology', level: 5 },
    { word: 'microscopic', level: 7 },
    { word: 'macroscopic', level: 8 },
    { word: 'microphone', level: 4 },
    { word: 'megalith', level: 5 },
    { word: 'monolith', level: 3 },
    { word: 'microlith', level: 5 }
  ]
}